FROM composer:1.7.2

RUN apk add --no-cache nodejs

COPY TestLibrary.deps.json /dotnet/TestLibrary.deps.json
COPY composer_laravel.lock /php-app/composer.lock
COPY Gemfile_rails.lock /ruby-app/Gemfile.lock
COPY package-lock_react.json /node-app/package-lock.json
COPY package.json /node-app2/package.json
COPY yarn.lock /yarn/yarn.lock
COPY Pipfile.lock /python-app/Pipfile.lock
COPY requirements.txt /python-app2/requirements.txt
COPY poetry.lock /python-app3/poetry.lock
COPY Cargo.lock /rust-app/Cargo.lock
COPY kubectl /bin/kubectl

# Attempt to avoid OS detection
RUN echo -e 'PRETTY_NAME="Linux"\nNAME="Linux"\nVERSION_ID="99"\nVERSION="99 (honk)"\nID=Linux' > /etc/os-release
RUN rm -f /etc/lsb-release
RUN rm -f /etc/alpine-release

# Delete the APK metadata and package cache
RUN rm -rf /etc/apk
RUN rm -rf /lib/apk
